[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "caicpy"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp == 3.8.*",
    "beautifulsoup4==4.12.*",
    "requests == 2.30.*",
    "pydantic==2.*",
    "python-dateutil==2.8.*",
]

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]
